# Generated by Django 3.0 on 2022-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, default=None, help_text='User who create the record', max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, default=None, help_text='User who update the record', max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['id'], name='contact_con_id_ec4de3_idx'),
        ),
    ]
