# Generated by Django 3.0 on 2022-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, default=None, help_text='User who create the record', max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, default=None, help_text='User who update the record', max_length=100, null=True)),
                ('room_type', models.CharField(help_text='Room type name', max_length=50)),
                ('price_per_night', models.FloatField(help_text='Price per night for each room')),
                ('max_guest', models.IntegerField(help_text='Maximum number of guests per room')),
                ('stock', models.IntegerField(help_text='Stock available for booking')),
                ('stock_reserves', models.IntegerField(default=0, help_text='Total reserved stock units', null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='rooms',
            index=models.Index(fields=['id'], name='rooms_rooms_id_56f8da_idx'),
        ),
    ]
