# Generated by Django 3.0 on 2022-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image_url',
            field=models.CharField(blank=True, help_text='Room image', max_length=225, null=True),
        ),
    ]
