# Generated by Django 3.0 on 2022-04-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, default=None, help_text='User who create the record', max_length=100, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, default=None, help_text='User who update the record', max_length=100, null=True)),
                ('check_in', models.DateField(help_text='Hotel check-in day')),
                ('check_out', models.DateField(help_text='Hotel check-out day')),
                ('number_of_guests', models.IntegerField(help_text='Number of guests in the reservation')),
                ('total_price', models.FloatField(help_text='Total price of the booking')),
                ('locator', models.CharField(help_text='Unique reserve locator', max_length=10, unique=True)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['id'], name='bookings_bo_id_3b312a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['room', 'contact'], name='bookings_bo_room_id_be341a_idx'),
        ),
    ]
